# Generated by Django 3.2.6 on 2022-05-31 23:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_auto_20220531_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='PhoneNumber',
        ),
    ]
